name: flutter_app_project_miaged
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.0-308.0.dev <4.0.0'

dependencies:
  firebase_auth: ^4.2.10
  firebase_core: ^2.7.1
  flutter:
    sdk: flutter
  flutter_native_splash: ^2.2.19
  flutter_riverpod: ^2.3.1
  go_router: ^6.2.0
  google_nav_bar: ^5.0.6

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

#Run commands to generete splash screen
# 1) flutter clean
# 2) flutter pub get
# 3) flutter pub run flutter_native_splash:create
# or do flutter clean&flutter pub get&flutter pub run flutter_native_splash:create
flutter_native_splash:
  # background_image: "assets/glass_bg_2.png"
  # color: "#ffffff"
  # color: "#0D0D0D"
  color: "#242B2E"
  # color: "#89C4F4"
  image: assets/icon_flutter_wht.png
  # branding: "assets/icon_flutter.png"

flutter:
  uses-material-design: true
  assets:
    - assets/
