// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDLlXUkaY8deKpXuMrA2x5qlYc1tUfw54U',
    appId: '1:675898728685:web:2d5d523ef5071414c96ce4',
    messagingSenderId: '675898728685',
    projectId: 'fir-miaged',
    authDomain: 'fir-miaged.firebaseapp.com',
    storageBucket: 'fir-miaged.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBOcfaI2jhQw4aGhjruJ70Uaqb6acbM5wo',
    appId: '1:675898728685:android:f6b16ece768bb9d8c96ce4',
    messagingSenderId: '675898728685',
    projectId: 'fir-miaged',
    storageBucket: 'fir-miaged.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCKE6Jq4DvfNQ3iOxaJyHPS2_Jkvf3Rkcs',
    appId: '1:675898728685:ios:b018eb8e328b42b1c96ce4',
    messagingSenderId: '675898728685',
    projectId: 'fir-miaged',
    storageBucket: 'fir-miaged.appspot.com',
    iosClientId:
        '675898728685-gb9tig1vnbd08mmu3huvr4gtjpdh2d00.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterAppProjectMiaged',
  );
}
